services:
    app:
        build: .
        volumes:
            - .:/app
        command: >
            bash -c '
                cd app
                mkdir -p build
                cd build
                cmake -G Ninja -S .. -DCMAKE_CXX_COMPILER=/usr/bin/clang -DCMAKE_CXX_FLAGS=-stdlib=libc++
                ninja -C .
                ./flower_neural_network
            '
