services:
    app:
        build: .
        volumes:
            - .:/src
        command: >
            bash -c '
                cd src
                mkdir -p build
                cmake -G Ninja -S . -B build -DCMAKE_CXX_COMPILER=/usr/bin/clang++ -DLIBCXX_BUILD=/llvm-project/build
                ninja -C build
                build/flower_neural_network
            '
